# Generated by Django 4.2.2 on 2023-08-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readit_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="books_read",
            field=models.ManyToManyField(
                blank=True, related_name="read_by", to="readit_app.book"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="books_want_to_read",
            field=models.ManyToManyField(
                blank=True, related_name="wanted_by", to="readit_app.book"
            ),
        ),
    ]
