# Generated by Django 4.2.2 on 2023-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readit_app", "0002_alter_userprofile_books_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="external_id",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
