# Generated by Django 4.2.2 on 2023-08-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readit_app", "0003_book_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="external_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
