# Generated by Django 4.2.2 on 2023-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readit_app", "0005_alter_book_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="external_id",
            field=models.CharField(blank=True, default=""),
        ),
    ]
