# Generated by Django 4.2.2 on 2023-08-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readit_app", "0006_alter_book_author_alter_book_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="book",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
